### ISSUE TITLE
hotkey or UI button to hide code

### ISSUE THREAD

**Issue by floer32** [shawnlawson/The_Force#13]
When I think about performing with this tool, I'm actually thinking about some pretty simple visuals with slow changes ... and only changing code sometimes. I like the idea of showing the code when I'm changing it, but maybe hiding it when I leave the code alone, and start playing with synths. To support a use-case like this, it could be cool to hide the code sometimes.

**Comment by shawnlawson** [comment]
I have CTRL + SHIFT bound to toggle text visibility. Was having issues with this feature going cross-platform. Does it work for you?

**Comment by floer32** [comment]
Huh! Look at that! I didn't realize. Thanks for letting me know :) It works for me but I am on OS X as well. (And indeed it's CTRL not CMD; and CTRL ought to work better cross platform I'd think ...)

Just asked my friend @hummus and he found the keybinding to work on Windows but not Linux (Ubuntu I think). He may chime in to clarify.

I would say let's just close this PR but maybe this is useful to Linux users?

**Comment by floer32** [comment]
Actually @hummus found it works on Linux too. So really no need. I'll just make sure the readme calls the keyboard shortcut out
