### ISSUE TITLE
fractal and turbulence

### ISSUE THREAD

**Issue by MaxBittker** [shawnlawson/The_Force#17]
these two functions are mentioned in the info, but don't appear to be defined. <3 love this tool by the way!

**Comment by shawnlawson** [comment]
Oh darn it. I need to update the html page. Changed the function names and over-rode them. The wiki has an up to date API
https://github.com/shawnlawson/The_Force/wiki/API

**Comment by MaxBittker** [comment]
thanks shawn! didn't know about the wiki at all, very useful (might be worth linking it in the readme). By the way - I've been craving bitwise operations but apparently they require OpenGL ES 3.0 - not knowing the landscape of webgl, what kind of work would be required to enable support for 3.0 and is it even ready for this kind of application?

**Comment by shawnlawson** [comment]
No problem!

Wow that's another glaring mistake. OK, clearly I need to work on these asap. 

Re OES 3.0: yeah, I would like it as well for some other things. But WebGL at this point is only OES 2.0. https://www.khronos.org/webgl/ Not sure what it would take to get the support, other than working for maybe google, mozilla, or another webgl consortium group. There is a repo https://github.com/KhronosGroup/WebGL But then, even those changes would need to be distributed by browser updates or maybe compiling your own version of chromium or firefox?

**Comment by MaxBittker** [comment]
got it - guess I'll look into emulating some of the masking that I want :/

**Comment by shawnlawson** [comment]
Hmmmm, what kind of masking? From an image, video, procedural content layer, the webGL canvas onto something else?

**Comment by shawnlawson** [comment]
It dawned on me that you may want to do bit-wise masking. You could figure out the operations using what is available like this post 
http://stackoverflow.com/questions/27548216/colour-bit-wise-shift-in-opengl-shader-glsl

Otherwise, I updated the html and readme, so I'll close this bug. If you want to talk about masking, let me know.

**Comment by MaxBittker** [comment]
thanks shawn, that's actually precisely what i needed! wanted to build a new render for https://maxbittker.github.io/

**Comment by shawnlawson** [comment]
Great! Oh, I really like the Mojulo gallery.

**Comment by MaxBittker** [comment]
@shawnlawson do you have any advice on exporting good quality video? made some things that I'm really happy with!

**Comment by shawnlawson** [comment]
@MaxBittker  . Was using Quicktime, but couldn't control their compression settings. @kindohm turned me on OBS, https://obsproject.com which has been great!

**Comment by MaxBittker** [comment]
wonderful, thank you! it was your HQ kindohm video on viemo that impressed me
