### ISSUE TITLE
None of the examples seem to work

### ISSUE THREAD

**Issue by bgenchel** [shawnlawson/The_Force#22]
Hi,

I've copied and pasted about half of the examples in the examples folder (The_Force/shaderExperiments) into the editor and none of them seem to work. They all just change the background color. That doesn't appear to be intended based on the name. Perhaps they need to be updated?

i'm using a macbook pro, Mojave 10.14.6
tried on both chrome (81.0.4044.129 (Official Build) (64-bit)) and firefox (68.6.1esr (64-bit))
same results.

**Comment by bgenchel** [comment]
i'm using a macbook pro, Mojave 10.14.6
tried on both chrome (81.0.4044.129 (Official Build) (64-bit)) and firefox (68.6.1esr (64-bit)) 
same results.

**Comment by bgenchel** [comment]
Hi, 

Figured out the problem - they all seem to require audio in, which you need to set up manually. I'm going to close this for now, but I think it'd be nice if you put that in the description along side the link :)

**Comment by shawnlawson** [comment]
Good point, thanks! Updated examples with audio portion commented out and instructions.
