### ISSUE TITLE
Please respect the license

### ISSUE THREAD

**Issue by stegu** [shawnlawson/The_Force#38]
You are using a noise implementation from github/stegu/webgl-noise (formerly github/ashima/webgl-noise, which is now unmaintained). Please respect the MIT license and give credit. All you need to do is not delete the author information. You might want to consider listing us in your section "sources" as well. Thanks for your consideration - all we ask for is proper credit.

**Comment by shawnlawson** [comment]
Added reference link to sources and made a copy of the webgl-noise license into the licenses folder. Hopefully fulfills credit expectation.

**Comment by stegu** [comment]
Thank you! As a scientist, credit is my lifeblood. Keeping a comment in the
source is enough, no sweat.

Den tors 28 nov. 2024 17:47Shawn Lawson ***@***.***> skrev:
