### ISSUE TITLE
Create better documentation 

### ISSUE THREAD

**Issue by shawnlawson** [shawnlawson/The_Force#4]
put in wiki and within the_force

**Comment by hangtwenty** [comment]
@kevincairo

**Comment by floer32** [comment]
@kevincairo and I just hosted workshop about some livecoding things at [Dadaconf 0.1](http://dadaconf.com/). Our group wound up coding together, **mostly using The Force** for hours and hours and hours. Some of us were at it for over 8 hours. Haha. It was wonderful. (Conference just ended but we will try to gather some things we were doing, I'm sure you'd get a kick out of seeing what people got into.)

This markdown document was the prompt/resource for the participants: https://github.com/hangtwenty/dadaconf-livecoding-guide

In case that helps at all with documentation-creation, or maybe just something to point to in the meantime.

**Comment by shawnlawson** [comment]
Whoa, no way, that's awesome! I think I'm going to have more time to work on things pretty soon. If you haven't seen Patricio's book, you might want to check it out, https://github.com/patriciogonzalezvivo/thebookofshaders
Some of the variables have different names, so you'll have to watch closely if you copy/paste code into the_force.

**Comment by floer32** [comment]
oh wow. @patriciogonzalezvivo WOW WOW WOW this is going to be so much fun :)

**Comment by patriciogonzalezvivo** [comment]
Hi! Nice editor! I have been working on an editor too ( http://editor.thebookofshaders.com ) and I'm curious to know more about your approach and the ideas behind it.
Good luck in the conference looks super fun!

**Comment by shawnlawson** [comment]
Nice! I've been following the book, but didn't know about the editor. Holy cow those popup UI elements. We should grab a coffee next time I come down to the city.

**Comment by shawnlawson** [comment]
API reference finally added.
