### ISSUE TITLE
Mic/Line Input fails without https

### ISSUE THREAD

**Issue by kevinkyyro** [shawnlawson/The_Force#9]
Chrome doesn't seem to ask for permission to use mic input on http sites, so might be worth redirecting http to https?

Alternatively, the error message when it fails could suggest trying again after loading over https.

**Comment by shawnlawson** [comment]
OH! Good point. Fixed the link at the top of repo page. Will look at adding that in.

Thanks.

**Comment by shawnlawson** [comment]
Added a quick check when opening microphone to see if the protocol is https. Does not auto-redirect, because someone may want to copy their code first and it may break things if someone is running http local if I require https.
